### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by zyberg2091** [arnoob16/GeeksForGeeksAPI#1]
app.py is named as server.py in documentation. Please check it once.

![error](https://user-images.githubusercontent.com/42847318/103419688-084a0100-4bba-11eb-89d5-9f89cb12308e.png)

**Comment by arnoob16** [comment]
I haven't set up the `contributions guidelines` for the project yet. 
If you are familiar with standard contribution guidelines of sending a PR, I can assign this issue to you if you are interested.

**Comment by zyberg2091** [comment]
sure, can you assign me this issue?

**Comment by rutvikpadhiyar000** [comment]
Also add optional url  *http://localhost:5000/yourGeeksForGeeksUsername*

**Comment by arnoob16** [comment]
@zyberg2091 since you haven't made a PR yet, can you add the optional URL as @rutvikpadhiyar000 suggested.

**Comment by zyberg2091** [comment]
@arnoob16 I will do it

**Comment by arnoob16** [comment]
Issue Closed with #4 , Thanks for your contribution @zyberg2091 & @rutvikpadhiyar000
