### ISSUE TITLE
Receiving "error": "Profile Not Found" even on correct username

### ISSUE THREAD

**Issue by localhost-8000** [arnoob16/GeeksForGeeksAPI#9]

**Comment by Prashanth820** [comment]
Same Issue.

**Comment by Kush-munot** [comment]
Same Issue Needs to be resolved

**Comment by VandeshSawant** [comment]
Yes its even showing authors profile is not found

**Comment by AnitSarkar123** [comment]
Same issue

**Comment by arnoob16** [comment]
Sorry to everyone for the long delay, but it's fixed now.

**Comment by technoayan7** [comment]
Still facing same issue

**Comment by technoayan7** [comment]
// 20240308025511
// https://geeks-for-geeks-api.vercel.app/technoayan7

{
  "message": "Internal Server Error"
}
